apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: devops
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
