---
apiVersion: v1
kind: ConfigMap
metadata:
  name: questcode
  namespace: prod
data:
  NODE_ENV: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: questcode
  namespace: staging
data:
  NODE_ENV: staging
---